---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: etcd
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: etcd
spec:
  selector:
    matchLabels:
      app: etcd
  replicas: 1
  template:
    metadata:
      labels:
        app: etcd
    spec:
      hostname: etcd
      containers:
        - name: etcd
          securityContext:
            allowPrivilegeEscalation: false
            runAsUser: 0
          image: bitnami/etcd:3.4.9-debian-10-r21

          volumeMounts:
          - mountPath: /bitnami/etcd/data
            name: etcd-data
          env:
          - name: ETCD_ROOT_PASSWORD
            value: "123456a@"
          - name: ETCD_DATA_DIR
            value: "/bitnami/etcd/data/restoreddata"
          ports:
            - containerPort: 2379
      volumes:
      - name: etcd-data
        persistentVolumeClaim:
          claimName: etcd
---
apiVersion: v1
kind: Service
metadata:
  name: etcd
  labels:
    app: etcd
spec:
  ports:
    - port: 2379
      targetPort: 2379
  selector:
    app: etcd


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: etcdkeeper
spec:
  selector:
    matchLabels:
      app: etcdkeeper
  replicas: 1
  template:
    metadata:
      labels:
        app: etcdkeeper
    spec:
      containers:
        - name: etcdkeeper
          image: dockerhub.dttt.vn/etcdkeeper

          ports:
            - containerPort: 8080
      imagePullSecrets:
      - name: dockerhubdtttvn
---
apiVersion: v1
kind: Service
metadata:
  name: etcdkeeper
  labels:
    app: etcdkeeper
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: etcdkeeper


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
spec:
  selector:
    matchLabels:
      app: rabbitmq
  replicas: 1
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:3-management-alpine

          volumeMounts:
          - mountPath: /var/lib/rabbitmq
            name: rabbitmq
          env:
          - name: HOSTNAME
            value: "rabbitmq"
          ports:
            - containerPort: 5672
            - containerPort: 15672
      volumes:
        - name: rabbitmq
          hostPath:
            path: /volumes/rabbitdata/
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  labels:
    app: rabbitmq
spec:
  type: LoadBalancer
  ports:
    - port: 15672
      name: port1
      targetPort: 15672
    - port: 5672
      name: port2
      targetPort: 5672
  selector:
    app: rabbitmq


---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
data:

  redis.conf: |
    user root on allkeys allchannels allcommands >VgJyAzye2YZIz3nT

    user default off  

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  selector:
    matchLabels:
      app: redis
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:6.2.6-alpine

          command: ["/bin/sh"]
          args: ["-c", "while true; do redis-server /usr/local/etc/redis/redis.conf; sleep 10;done"]
          resources:
            requests:
              memory: "1500Mi"
              cpu: 2
            limits:
              memory: "3000Mi"
              cpu: 4          
          volumeMounts:
          - mountPath: /data
            name: redis-data
          - mountPath: /usr/local/etc/redis
            name: redis-config
          env:
          - name: HOSTNAME
            value: "redis"
          ports:
            - containerPort: 6379
      volumes:
      - name: redis-data
        persistentVolumeClaim:
          claimName: redis
      - name: redis-config
        configMap:
          name: redis-config
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: redis
spec:
  type: LoadBalancer
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    app: redis

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: documentserver
spec:
  selector:
    matchLabels:
      app: documentserver
  replicas: 1
  template:
    metadata:
      labels:
        app: documentserver
    spec:
      containers:
        - name: documentserver
          image: dockerhub.dttt.vn/documentserver:3.0
          imagePullPolicy: Always
          ports:
            - containerPort: 80
      imagePullSecrets:
      - name: dockerhubdtttvn
---
apiVersion: v1
kind: Service
metadata:
  name: documentserver
  labels:
    app: documentserver
spec:
  type: LoadBalancer
  ports:
    - port: 9201
      targetPort: 80
  selector:
    app: documentserver
