apiVersion: v1
kind: PersistentVolume
metadata:
  name: etcd
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 10Gi
  hostPath:
    path: /volumes/etcd/
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: etcd
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: etcd
spec:
  selector:
    matchLabels:
      app: etcd
  replicas: 1
  template:
    metadata:
      labels:
        app: etcd
    spec:
      hostname: etcd
      containers:
        - name: etcd
          securityContext:
            allowPrivilegeEscalation: false
            runAsUser: 0
          image: bitnami/etcd:3.4.9-debian-10-r21
          volumeMounts:
          - mountPath: /bitnami/etcd/data
            name: etcd
          env:
          - name: ETCD_ROOT_PASSWORD
            value: "123456a@"
          - name: ETCD_DATA_DIR
            value: "/bitnami/etcd/data/restoreddata"
          ports:
            - containerPort: 2379
      volumes:
      - name: etcd
        persistentVolumeClaim:
          claimName: etcd
---
apiVersion: v1
kind: Service
metadata:
  name: etcd
  labels:
    app: etcd
spec:
  type: NodePort
  ports:
    - port: 2379
      nodePort: 30003
  selector:
    app: etcd
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: etcdkeeper
spec:
  selector:
    matchLabels:
      app: etcdkeeper
  replicas: 1
  template:
    metadata:
      labels:
        app: etcdkeeper
    spec:
      containers:
        - name: etcdkeeper
          image: dockerhub.dttt.vn/etcdkeeper
          ports:
            - containerPort: 8080
      imagePullSecrets:
      - name: dockerhubdtttvn
---
apiVersion: v1
kind: Service
metadata:
  name: etcdkeeper
  labels:
    app: etcdkeeper
spec:
  type: NodePort
  ports:
    - port: 8080
      nodePort: 30004
  selector:
    app: etcdkeeper

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: rabbitmq
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 10Gi
  hostPath:
    path: /volumes/rabbitmq/
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rabbitmq
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
spec:
  selector:
    matchLabels:
      app: rabbitmq
  replicas: 1
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:3-management-alpine
          volumeMounts:
          - mountPath: /var/lib/rabbitmq
            name: rabbitmq
          env:
          - name: HOSTNAME
            value: "rabbitmq"
          ports:
            - containerPort: 5672
            - containerPort: 15672
      volumes:
      - name: rabbitmq
        persistentVolumeClaim:
          claimName: rabbitmq
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  labels:
    app: rabbitmq
spec:
  type: NodePort
  ports:
    - port: 15672
      nodePort: 30005
  selector:
    app: rabbitmq

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
data:
  # property-like keys; each key maps to a simple value
  #ui_properties_file_name: "redis.conf"

  # file-like keys
  redis.conf: |
    user root on allkeys allchannels allcommands >VgJyAzye2YZIz3nT

    user default off  

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 10Gi
  hostPath:
    path: /volumes/redis/
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  selector:
    matchLabels:
      app: redis
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:6.2.6-alpine
          command: ["/bin/sh"]
          args: ["-c", "while true; do redis-server /usr/local/etc/redis/redis.conf; sleep 10;done"]
          resources:
            requests:
              memory: "1500Mi"
              cpu: 2
            limits:
              memory: "3000Mi"
              cpu: 4          
          volumeMounts:
          - mountPath: /data
            name: redis
          - mountPath: /usr/local/etc/redis
            name: redis-config
          env:
          - name: HOSTNAME
            value: "redis"
          ports:
            - containerPort: 6379
      volumes:
      - name: redis
        persistentVolumeClaim:
          claimName: redis
      - name: redis-config
        configMap:
          name: redis-config
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: redis
spec:
  type: NodePort
  ports:
    - port: 6379
      nodePort: 30006
  selector:
    app: redis

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: documentserver
spec:
  selector:
    matchLabels:
      app: documentserver
  replicas: 1
  template:
    metadata:
      labels:
        app: documentserver
    spec:
      containers:
        - name: documentserver
          image: dockerhub.dttt.vn/documentserver:3.0
          ports:
            - containerPort: 80
      imagePullSecrets:
      - name: dockerhubdtttvn
---
apiVersion: v1
kind: Service
metadata:
  name: documentserver
  labels:
    app: documentserver
spec:
  type: NodePort
  ports:
    - port: 80
      nodePort: 30008
  selector:
    app: documentserver
