---
- hosts: master
  ignore_unreachable: yes
  ignore_errors: yes
  remote_user: root
  tasks:
  - name: deploy infra
    shell: kubectl apply -f ./ansible/kubernetes/infra/infra.yaml -f ./ansible/kubernetes/infra/thumbor-var.yaml