---
- hosts: " {{ HostNameOrGroupReachable }} "
  ignore_unreachable: yes
  ignore_errors: yes
  remote_user: root
  vars_files:
    - variables.yml
  tasks:
    - name: set up date time
      shell: |
        DEBIAN_FRONTEND='noninteractive' apt-get -y -o Dpkg::Options::='--force-confdef' -o Dpkg::Options::='--force-confold' upgrade
        DEBIAN_FRONTEND='noninteractive' apt-get -y -o Dpkg::Options::='--force-confdef' -o Dpkg::Options::='--force-confold' dist-upgrade    
        apt-get autoremove -y
        apt-get clean
        apt-get autoclean
        timedatectl set-timezone Asia/Ho_Chi_Minh
        hwclock --hctosys
        hwclock --systohc
        timedatectl set-ntp on
      
    - name: Install a list of packages with a list variable
      package:
        name: "{{ packages }}"
        state: present
        update_cache: yes
      vars:
        packages:
          - htop
          - telnet
          - wget
          - cockpit
          - net-tools
          - nfs-common
          - python3
          - git
      

    - name: Install aptitude
      apt:
        name: aptitude
        state: latest
        update_cache: true
      

    - name: Install required system packages
      apt:
        pkg:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - python3-pip
          - virtualenv
          - python3-setuptools
        state: latest
        update_cache: true
      

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
      

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu focal stable
        state: present
      

    - name: Update apt and install docker-ce
      apt:
        name: docker-ce
        state: latest
        update_cache: true
      

    - name: Install Docker Module for Python
      pip:
        name: docker

    - name: used ufw
      shell: |
        sudo ufw default deny incoming
        sudo ufw default allow outgoing
        sudo ufw allow OpenSSH
        sudo ufw allow 80
        sudo ufw allow 443
        sudo ufw allow 2376/tcp
        sudo ufw allow 2377/tcp
        sudo ufw allow 7946/tcp
        sudo ufw allow 4789/udp
        sudo ufw allow 7946/udp
        sudo ufw allow 9001/tcp
        sudo ufw --force enable      

    #Controls systemd services on remote hosts.
    - name: Insert data to daemon.json
      shell: |
        printf '{
          "insecure-registries": [
            "dockerhub.dttt.vn"
          ],
          "data-root":"/'"{{data_of_docker}}"'/docker",
          "log-driver": "gelf",
          "log-opts": {
            "gelf-address": "udp://localhost:12201"
          },
          "metrics-addr": "0.0.0.0:9323"
        }' > /etc/docker/daemon.json
      
      tags: daemon
      


    - name: Restart service docker, in all cases, also issue daemon-reload to pick up config changes
      ansible.builtin.systemd:
        state: restarted
        daemon_reload: yes
        enabled: yes
        name: docker
      
    - name: login dockerhub.dttt.vn
      docker_login:
        registry: dockerhub.dttt.vn
        username: "{{userdockerhub}}"
        password: "{{passworddockerhub}}"
        reauthorize: yes      
      tags: login

    - name: Copy file with owner and permissions
      ansible.builtin.copy:
        src: /home/token/
        dest: /home
        owner: root
        group: root
        mode: '0777'
      tags: manager    

#    - name: Remove a swarm
#      shell: docker swarm leave -f
#      tags: manager      

    - name: remove the error character
      shell: sed -n -i -e '/docker/,$p' /home/manager.sh
      tags: manager
    - name: remove the error character
      shell: sed "s/^[ \t]*//" -i /home/manager.sh
      tags: manager
    - name: join manager(Reachable) docker swarm
      shell: /home/manager.sh
      tags: manager

 # Config limit parameters
    - name: Config limit parameters soft
      shell: echo "*    soft    nofile 819200" >>/etc/security/limits.conf
      
    - name: Config limit parameters hard
      shell: echo "*    hard    nofile 819200" >>/etc/security/limits.conf
      
    - name: Config limit parameters touch
      shell: touch /etc/security/limits.conf
      
    - name: Config limit parameters file-max
      shell: echo "fs.file-max = 200000" >>/etc/sysctl.conf
      
    - name: Config limit parameters inotify.max_user_watches
      shell: echo "fs.inotify.max_user_watches = 2048576" >>/etc/sysctl.conf
      
    - name: Config limit parameters inotify.max_user_instances
      shell: echo "fs.inotify.max_user_instances = 524288" >>/etc/sysctl.conf