---
- hosts: "{{ HostInstallPortainer }}"
  ignore_unreachable: yes
  ignore_errors: yes
  remote_user: root
  vars_files:
    - variables.yml
  tasks:

    - name: This module will replace all instances of a pattern within a file
      ansible.builtin.replace:
        path: /home/setup/infrastructure.yml
        regexp: 'manager'
        replace: 'worker'
      tags: managertoworker

    - name: This module will replace all instances of a pattern within a file
      ansible.builtin.replace:
        path: /home/setup/traefik.yml
        regexp: 'manager'
        replace: 'worker'
      tags: managertoworker