---
- hosts: kubernetes_cluster
  ignore_unreachable: yes
  ignore_errors: yes
  become: true
  become_method: enable
  vars_files:
    - ./vars.yaml
  tasks:
  - name: hosts file
    shell: |
      tee /etc/hosts << EOF
      127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4
      ::1         localhost localhost.localdomain localhost6 localhost6.localdomain6
      
      10.1.20.248             git.ecomedic.vn
      {{masterip}} k8s-master
      {{workerip}} k8s-worker
      EOF

  - name: kubernetes repo
    shell: |
      tee /etc/yum.repos.d/kubernetes.repo<<EOF
      [kubernetes]
      name=Kubernetes
      baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
      enabled=1
      gpgcheck=1
      repo_gpgcheck=1
      gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
      EOF

  - name: clear
    shell: yum clean all && yum -y makecache

  - name: install kube
    shell: yum -y install epel-release vim git curl wget kubelet-1.26.3-0 kubeadm-1.26.3-0 kubectl-1.26.3-0 --disableexcludes=kubernetes

  - name: Remove swapfile from /etc/fstab
    mount:
      name: "{{ item }}"
      fstype: swap
      state: absent
    with_items:
      - swap
      - none

  - name: Disable swap
    command: swapoff -a
    when: ansible_swaptotal_mb > 0

  - name: modprobe
    shell: |
      modprobe overlay
      modprobe br_netfilter

  - name: kubernetes.conf
    shell: |
      tee /etc/sysctl.d/kubernetes.conf<<EOF
      net.bridge.bridge-nf-call-ip6tables = 1
      net.bridge.bridge-nf-call-iptables = 1
      net.ipv4.ip_forward = 1
      EOF

  - name: sysctl
    shell: sysctl --system

  - name: Configure persistent loading of modules
    shell: |
      tee /etc/modules-load.d/containerd.conf <<EOF
      overlay
      br_netfilter
      EOF

  - name: Load at runtime
    shell: |
      modprobe overlay
      modprobe br_netfilter

  - name: Ensure sysctl params are set
    shell: |
      tee /etc/sysctl.d/kubernetes.conf<<EOF
      net.bridge.bridge-nf-call-ip6tables = 1
      net.bridge.bridge-nf-call-iptables = 1
      net.ipv4.ip_forward = 1
      EOF

  - name: Reload configs
    shell: sysctl --system

  - name: Install required packages
    shell: yum install -y yum-utils device-mapper-persistent-data lvm2

  - name: Add Docker repo
    shell: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo

  - name: Install containerd
    shell: yum update -y && yum install -y containerd.io

  - name: Configure containerd and start service
    shell: |
      mkdir -p /etc/containerd
      containerd config default > /etc/containerd/config.toml

  - name: Configure containerd and start service
    shell: |
      mkdir -p /etc/containerd
      containerd config default > /etc/containerd/config.tom

  - name: Configure containerd and start service
    shell: |
      systemctl restart containerd
      systemctl enable containerd

  - name: Configure containerd and start service
    shell: systemctl disable --now firewalld

  - name: Configure containerd and start service
    shell: systemctl enable kubelet

  - name: docker
    shell: |
      yum install -y docker
      systemctl start docker
      sudo curl -L "https://github.com/docker/compose/releases/download/1.23.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
      sudo chmod +x /usr/local/bin/docker-compose