---
- hosts: worker
  ignore_unreachable: yes
  ignore_errors: yes
  become: true
  tasks:
  - name: Copy the join command to server location
    copy: src=join-command dest=/tmp/join-command.sh mode=0777

  - name: Join the node to cluster
    shell: sh /tmp/join-command.sh