---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: clear-nginx-deployment
spec:
  selector:
    matchLabels:
      app: clear-nginx
  template:
    metadata:
      labels:
        app: clear-nginx
    spec:
      initContainers:
      - name: webcontent
        image: busybox
        volumeMounts:
        - name: web-content
          mountPath: "/volumes/clear-nginx/"
        command: ["/bin/sh", "-c", 'echo "<h1>I am <font color=green>GREEN</font></h1>" > /webdata/index.html']
      containers:
      - name: clear-nginx
        image: clearlinux/nginx
        volumeMounts:
        - mountPath: /var/www/html
          name: web-content
        ports:
        - containerPort: 80
      volumes:
        - name: web-content
          hostPath: # hostPath volume
            path: /volumes/clear-nginx/
---
apiVersion: v1
kind: Service
metadata:
  name: clear-nginx-service
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30050
  selector:
    app: clear-nginx
  type: NodePort