---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: clear-nginx-deployment
spec:
  selector:
    matchLabels:
      app: clear-nginx
  template:
    metadata:
      labels:
        app: clear-nginx
    spec:
      containers:
      - name: clear-nginx
        image: clearlinux/nginx
        command: ["/bin/sh", "-c", 'echo "<h1>I am <font color=green>KHOA</font></h1>" > /var/www/html/index.html']
        volumeMounts:
        - mountPath: /var/www/html
          name: html
        ports:
        - containerPort: 80
      volumes:
        - name: html
          hostPath: # hostPath volume
            path: /volumes/clear-nginx/
---
apiVersion: v1
kind: Service
metadata:
  name: clear-nginx-service
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30050
  selector:
    app: clear-nginx
  type: NodePort