---
- hosts: leader
  become: true
  ignore_unreachable: yes
  ignore_errors: yes
  tasks:
  - name: Initialize the Kubernetes cluster using kubeadm
    command: kubectl create secret docker-registry dockerhubdtttvn --docker-server=dockerhub.dttt.vn --docker-username=admin --docker-password=Trinam@2019 --docker-email=admin@trinam.com.vn
    tags: k