---
- hosts: master
  become: true
  ignore_unreachable: yes
  ignore_errors: yes
  tasks:

  - name: Initialize the Kubernetes cluster using kubeadm
    shell: kubeadm config images pull
  - name: Initialize the Kubernetes cluster using kubeadm
    shell: kubeadm init
    tags: init

  - name: Setup kubeconfig for  user
    shell: "{{ item }}"
    with_items:
      - mkdir -p $HOME/.kube
      - sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
    tags: s1

  - name: Setup kubeconfig for  user 2
    shell: sudo chown $(id -u):$(id -g) $HOME/.kube/config
    tags: s2

  - name: Generate join command
    shell: kubeadm token create --print-join-command
    register: join_command
    tags: s3

  - name: Copy join command to local file
    local_action: copy content="{{ join_command.stdout_lines[0] }}" dest="./join-command"
    tags: s3

  - name: Install calico pod network
    shell: |
      curl https://projectcalico.docs.tigera.io/manifests/calico.yaml -O
      kubectl apply -f calico.yaml
    tags: s4