---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: identityserver-deployment
spec:
  selector:
    matchLabels:
      app: identityserver
  replicas: 1
  template:
    metadata:
      labels:
        app: identityserver
    spec:
      containers:
        - name: identityserver
          image: dockerhub.dttt.vn/core/identityserver:5.1
          env:
          - name: SCOPE__ENVIRONMENT
            value: "Test"
          - name: SCOPE__NAME
            value: "U2210"
          - name: ETCD__CONFIG
            value: "authenticated=true;server=http://10.0.68.171:2379;username=root;password=123456a@"
          - name: IDENTITYSERVER_LOGIN_LOGO
            value: "https://hdkhoa.example.com/admin/assets/environments/logo.png"
          - name: IDENTITYSERVER_LOGIN_TITLE
            value: "VIETINBANK"
          - name: IDENTITYSERVER_LOGIN_ADDRESS
            value: ""
          - name: IDENTITYSERVER_LOGIN_EMAIL
            value: ""
          - name: IDENTITYSERVER_LOGIN_FAX
            value: ""
          - name: IDENTITYSERVER_LOGIN_PHONE
            value: ""
          - name: IDENTITYSERVER_LOGO_NAME_EN
            value: ""
          - name: IDENTITYSERVER_LOGO_NAME_VN
            value: "VIETINBANK"
          - name: PUBLIC_ORIGIN
            value: "https://hdkhoa.example.com"
          - name: IDENTITYSERVER_LOGIN_HOMEPAGE
            value: "https://hdkhoa.example.com"
          ports:
            - containerPort: 80
      imagePullSecrets:
      - name: dockerhubdtttvn
---
apiVersion: v1
kind: Service
metadata:
  name: identityserver-service
  labels:
    app: identityserver
spec:
  ports:
    - port: 80
  selector:
    app: identityserver