---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ruletrackingapi-deployment
spec:
  selector:
    matchLabels:
      app: ruletrackingapi
  replicas: 1
  template:
    metadata:
      labels:
        app: ruletrackingapi
    spec:
      containers:
        - name: ruletrackingapi
          image: dockerhub.dttt.vn/core/ruletracking.api:5.0
          env:
          - name: SCOPE__ENVIRONMENT
            value: "Test"
          - name: SCOPE__NAME
            value: "U2210"
          - name: ETCD__CONFIG
            value: "authenticated=true;server=http://10.0.68.171:2379;username=root;password=123456a@"
      imagePullSecrets:
      - name: dockerhubdtttvn

---
apiVersion: v1
kind: Service
metadata:
  name: ruletracking-service
  labels:
    app: ruletrackingapi
spec:
  ports:
    - port: 80
  selector:
    app: ruletrackingapi
