---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: slogapi-deployment
spec:
  selector:
    matchLabels:
      app: slogapi
  replicas: 1
  template:
    metadata:
      labels:
        app: slogapi
    spec:
      containers:
        - name: slogapi
          image: dockerhub.dttt.vn/core/slog.api:5.1
          imagePullPolicy: Always
          env:
          - name: SCOPE__ENVIRONMENT
            value: "Test"
          - name: SCOPE__NAME
            value: "U2212"
          - name: ETCD__CONFIG
            value: "authenticated=true;server=http://etcd:2379;username=root;password=123456a@"
          ports:
            - containerPort: 80
      imagePullSecrets:
      - name: dockerhubdtttvn

---
apiVersion: v1
kind: Service
metadata:
  name: slog-service
  labels:
    app: slogapi
spec:
  ports:
    - port: 80
  selector:
    app: slogapi
