---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: uniquenumberapi-deployment
spec:
  selector:
    matchLabels:
      app: uniquenumberapi
  replicas: 1
  template:
    metadata:
      labels:
        app: uniquenumberapi
    spec:
      containers:
        - name: uniquenumberapi
          image: dockerhub.dttt.vn/core/uniquenumber.api:5.1
          env:
          - name: SCOPE__ENVIRONMENT
            value: "Test"
          - name: SCOPE__NAME
            value: "U2210"
          - name: ETCD__CONFIG
            value: "authenticated=true;server=http://10.0.68.171:2379;username=root;password=123456a@"
      imagePullSecrets:
      - name: dockerhubdtttvn

---
apiVersion: v1
kind: Service
metadata:
  name: uniquenumber-service
  labels:
    app: uniquenumberapi
spec:
  ports:
    - port: 80
  selector:
    app: uniquenumberapi
