---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: userclient-deployment
spec:
  selector:
    matchLabels:
      app: userclient
  replicas: 1
  template:
    metadata:
      labels:
        app: userclient
    spec:
      containers:
        - name: userclient
          image: dockerhub.dttt.vn/u202001/user.client:5.1
          imagePullPolicy: Always
          env:
          - name: BASE_HREF
            value: "/userv5"
          - name: APP_CODE
            value: "USER"
          - name: CONFIG_SERVICE
            value: ""
          ports:
            - containerPort: 80
          volumeMounts:
          - mountPath: /usr/share/nginx/html/assets/environments/
            name: client-data
      imagePullSecrets:
      - name: dockerhubdtttvn
      volumes:
      - name: client-data
        persistentVolumeClaim:
          claimName: client-data
---
apiVersion: v1
kind: Service
metadata:
  name: userclient-service
  labels:
    app: userclient
spec:
  ports:
    - port: 80
  selector:
    app: userclient